name: Nervos Official Production Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger a production deployment
        run: curl -X GET ${{ secrets.NERVOS_ORG_DEPLOYMENT_WEBHOOK }}
